POST http://localhost:3002/register
Content-Type: application/json

{
  "name": "Jeff Goes",
  "email": "goes.jeffjulian@gmail.com",
  "password": "kghtyujilop",
  "securityNumber": "40931363861"
}

###

GET http://localhost:3002/health

###