POST http://localhost:3002/register
Content-Type: application/json

{
  "name": "Jeff Goes",
  "email": "goes.jeffjulian@gmail.com",
  "password": "c8568k8g",
  "securityNumber": "40931363861"
}
###
GET http://localhost:3002/email/verification/234324324234

###
POST http://localhost:3002/refresh/token
Content-Type: application/json  

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvZXMuamVmZmp1bGlhbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY5OTIzMTN9.7G5Txvl6SJcRxIuLrj_cmEE7wXsPLybt2UKadLf3znc"
}

###
GET http://localhost:3002/customer/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvZXMuamVmZmp1bGlhbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY5OTY4NzAsImV4cCI6MTU5Njk5ODY3MH0.7TYykskN6sWf32stBLvvQ3jZjNxRhkadAWswjbHKGIs