POST http://localhost:3002/register
Content-Type: application/json

{
  "name": "Jeff Goes",
  "email": "goes.jeffjulian@gmail.com",
  "password": "c8568k8g",
  "securityNumber": "40931363861"
}
###
GET http://localhost:3002/email/verification/234324324234

###
POST http://localhost:3002/refresh/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvZXMuamVmZmp1bGlhbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY4NTA4MDN9.RhCL58wJqSVHr29UUznvJniUauIEV4eIZAVDwBpdo-A"
}

###
GET http://localhost:3002/customer/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvZXMuamVmZmp1bGlhbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY4NTYyNzAsImV4cCI6MTU5Njg1ODA3MH0.e4_MQB9UWjkxBSmlPkTWjdZOtWBDhfvIDRUqa2Ji03g